"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables: example first, then local .env to override
env_example = BASE_DIR / '.env.example'
env_local = BASE_DIR / '.env'
if env_example.exists():
    load_dotenv(env_example)
if env_local.exists():
    load_dotenv(env_local)

# If DATABASE_URL isn't provided, try to construct it from SUPABASE_* parts
if not os.getenv('DATABASE_URL'):
    supa_user = os.getenv('SUPABASE_DB_USER') or os.getenv('DB_USER')
    supa_pass = os.getenv('SUPABASE_DB_PASSWORD') or os.getenv('DB_PASSWORD')
    supa_host = os.getenv('SUPABASE_DB_HOST') or os.getenv('DB_HOST')
    supa_port = os.getenv('SUPABASE_DB_PORT') or os.getenv('DB_PORT')
    supa_name = os.getenv('SUPABASE_DB_NAME') or os.getenv('DB_NAME')
    if supa_user and supa_pass and supa_host and supa_port and supa_name:
        os.environ['DATABASE_URL'] = f"postgres://{supa_user}:{supa_pass}@{supa_host}:{supa_port}/{supa_name}"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-e8hx^nz&j8o7_%8(bh-&q1rh6!h%2^oj33^8#3tl026k2w(hu=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    'main',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_dj_db = dj_database_url.config(conn_max_age=600, ssl_require=True)
if _dj_db:
    DATABASES = {'default': _dj_db}
else:
    # Fallback to individual SUPABASE_* variables if DATABASE_URL isn't set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('SUPABASE_DB_NAME') or os.getenv('DB_NAME'),
            'USER': os.getenv('SUPABASE_DB_USER') or os.getenv('DB_USER'),
            'PASSWORD': os.getenv('SUPABASE_DB_PASSWORD') or os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('SUPABASE_DB_HOST') or os.getenv('DB_HOST'),
            'PORT': os.getenv('SUPABASE_DB_PORT') or os.getenv('DB_PORT'),
            'OPTIONS': {'sslmode': 'require'},
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



CORS_ALLOW_ALL_ORIGINS = True

